name: CI

on:
  push:
    branches: [main]

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Running ShellCheck
        uses: ludeeus/action-shellcheck@master
